name: Check and publish

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*.*'
  pull_request:
    branches:
      - "**"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14.0b2']
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Run deps install
      env:
        COMPOSE_FILE: "docker-compose.yml"
        CI_DC_DISABLE_TTY: "-T"
        PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
        make install-deps

  publish_pypi:
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref_type == 'tag'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Build
      run: make build
    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: make publish
